// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdN4IyVteLAWd3ooXa4nAjut0oly0r13o',
    appId: '1:913001562757:web:5a3acb87988d0bc0711fec',
    messagingSenderId: '913001562757',
    projectId: 'fooddata-c7e50',
    authDomain: 'fooddata-c7e50.firebaseapp.com',
    databaseURL: 'https://fooddata-c7e50-default-rtdb.firebaseio.com',
    storageBucket: 'fooddata-c7e50.appspot.com',
    measurementId: 'G-2VZD9C0Q4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXS2KsTgLydqC9p5_-fDV7M8cvDMtA7iw',
    appId: '1:913001562757:android:3530929930ef3987711fec',
    messagingSenderId: '913001562757',
    projectId: 'fooddata-c7e50',
    databaseURL: 'https://fooddata-c7e50-default-rtdb.firebaseio.com',
    storageBucket: 'fooddata-c7e50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMmuvcH0Pe4maeTDO5wQEXZrUIHqwmIKY',
    appId: '1:913001562757:ios:4bbab463ecd066e1711fec',
    messagingSenderId: '913001562757',
    projectId: 'fooddata-c7e50',
    databaseURL: 'https://fooddata-c7e50-default-rtdb.firebaseio.com',
    storageBucket: 'fooddata-c7e50.appspot.com',
    androidClientId: '913001562757-6kh2cvb3v06vp73aifn832hutve7nvlj.apps.googleusercontent.com',
    iosClientId: '913001562757-hd5tknrk1ocsh1u1o2hfijc7fmskv3jc.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventera',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdN4IyVteLAWd3ooXa4nAjut0oly0r13o',
    appId: '1:913001562757:web:05343508406ef656711fec',
    messagingSenderId: '913001562757',
    projectId: 'fooddata-c7e50',
    authDomain: 'fooddata-c7e50.firebaseapp.com',
    databaseURL: 'https://fooddata-c7e50-default-rtdb.firebaseio.com',
    storageBucket: 'fooddata-c7e50.appspot.com',
    measurementId: 'G-1SB02KJHPY',
  );

}