// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdN4IyVteLAWd3ooXa4nAjut0oly0r13o',
    appId: '1:913001562757:web:bc30abe611d650f7711fec',
    messagingSenderId: '913001562757',
    projectId: 'fooddata-c7e50',
    authDomain: 'fooddata-c7e50.firebaseapp.com',
    databaseURL: 'https://fooddata-c7e50-default-rtdb.firebaseio.com',
    storageBucket: 'fooddata-c7e50.appspot.com',
    measurementId: 'G-JJLKEKWSK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXS2KsTgLydqC9p5_-fDV7M8cvDMtA7iw',
    appId: '1:913001562757:android:535bd319858bcb1f711fec',
    messagingSenderId: '913001562757',
    projectId: 'fooddata-c7e50',
    databaseURL: 'https://fooddata-c7e50-default-rtdb.firebaseio.com',
    storageBucket: 'fooddata-c7e50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMmuvcH0Pe4maeTDO5wQEXZrUIHqwmIKY',
    appId: '1:913001562757:ios:35fd4d9e85e89a06711fec',
    messagingSenderId: '913001562757',
    projectId: 'fooddata-c7e50',
    databaseURL: 'https://fooddata-c7e50-default-rtdb.firebaseio.com',
    storageBucket: 'fooddata-c7e50.appspot.com',
    iosBundleId: 'com.example.eventProject01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdN4IyVteLAWd3ooXa4nAjut0oly0r13o',
    appId: '1:913001562757:web:138768810986d0cd711fec',
    messagingSenderId: '913001562757',
    projectId: 'fooddata-c7e50',
    authDomain: 'fooddata-c7e50.firebaseapp.com',
    databaseURL: 'https://fooddata-c7e50-default-rtdb.firebaseio.com',
    storageBucket: 'fooddata-c7e50.appspot.com',
    measurementId: 'G-8169B78CX6',
  );
}
